environment: production
lang: ru
title: Судэксперт
sity: test
phone: +7 (8482) 63-12-88
email: sud163@ya.ru
description: >- # this means to ignore newlines until "baseurl:"
  Независимая экспертиза и оценка имущества
permalink: /:categories/:year/:month/:day/:slug/
date_format: "%d.%m.%Yг."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jekyll.garibaldicastle.ru" # the base hostname & protocol for your site, e.g. http://example.com
telegram_api: "https://functions.yandexcloud.net/d4el63afa9h0t7ogmdt8"
plugins:
  - jekyll-sitemap

# sass:
#   style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

exclude:
  - LICENSE.txt
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/